name: Update Docs

permissions:
    contents: write
    pages: write

on:
    push:
        branches:
            - master

jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        outputs:
            package-name: ${{ steps.packageInfo.outputs.package-name }}
            package-version: ${{ steps.packageInfo.outputs.package-version }}
            commit-msg: ${{ steps.packageInfo.outputs.commit-msg }}
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4 # Updated to latest version for better reliability

            - name: Parsing Package Info
              id: packageInfo
              run: |
                  echo "package-name=$(jq -r .name package.json)" >> $GITHUB_OUTPUT
                  echo "package-version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
                  echo "commit-msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
              shell: bash

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4 # Updated to latest version
              with:
                  node-version: "18" # Specify a Node version for consistency (adjust as needed)

            - name: Install Dependencies
              run: yarn install # Changed to `yarn install` for clarity

            - name: Build Documentation
              run: yarn run docs

            - name: Publish to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_branch: gh-pages
                  publish_dir: ./docs
                  github_token: ${{ secrets.GITHUB_TOKEN }}
